### ISSUE TITLE
Nav bar is only fixed in the index.html

### ISSUE THREAD

**Issue by Hardwaregore** [SirAlexBigBrain/GrassBandits#11]
@TechDudie 
question mark php question mark
![FBFB44BA-CFE4-4C57-9CEF-7D8B2336F68E](https://user-images.githubusercontent.com/88296644/162331457-892c07f1-fa1d-4fd1-8ca8-8b52b23af9fa.png)

**Comment by TechDudie** [comment]
I KNOW IM FIXXING IT I DONT GIVE A BLEEP
