### ISSUE TITLE
Question mark php question mark

### ISSUE THREAD

**Issue by Hardwaregore** [SirAlexBigBrain/GrassBandits#12]

**Comment by TechDudie** [comment]
its an IFWAIM

N00B DUH

IM FWIKSING IT

**Comment by Hardwaregore** [comment]
@TechDudie 
Its `iframe` and `fixing` not `ifwaime` and `fwikseing`. Stop failing ELA and hand in ur anthological sheet. And also i heard that u got a 4/10 on ur writing assignment. Have fun!!!!!

**Comment by TechDudie** [comment]
thats it. shut up

**Comment by TechDudie** [comment]
__*This content has been restricted due to violation of our TOS.*__
