### ISSUE TITLE
I GOT A PAYPAL ACCOUNT!!

### ISSUE THREAD

**Issue by SirAlexBigBrain** [SirAlexBigBrain/GrassBandits#16]
Well, technically it is my mom’s, but it is one. I will tell you in school. I do not want to diverge this information to the public.

![A4DCFF33-0A05-49C3-800F-82A1625C4869](https://user-images.githubusercontent.com/98426972/165649572-36f23771-2390-4950-9205-2c4053b993f1.jpeg)

**Comment by SirAlexBigBrain** [comment]
Yeah!

**Comment by TechDudie** [comment]
lol
