### ISSUE TITLE
talk issue during test

### ISSUE THREAD

**Issue by TechDudie** [SirAlexBigBrain/GrassBandits#21]
[This content…]

**Comment by SirAlexBigBrain** [comment]
Hey yabo

**Comment by SirAlexBigBrain** [comment]
Please please please make a PayPal account.

**Comment by TechDudie** [comment]
okokok

**Comment by SirAlexBigBrain** [comment]
Thanks

**Comment by TechDudie** [comment]
remaking the website

**Comment by TechDudie** [comment]
https://github.com/TechDudie/GrassBandits

**Comment by SirAlexBigBrain** [comment]
What? Why

**Comment by TechDudie** [comment]
because its messy
im making it professional

**Comment by TechDudie** [comment]
like fixing the bar

**Comment by TechDudie** [comment]
check it out at https://techdudie.github.io/GrassBandits/template.html

**Comment by SirAlexBigBrain** [comment]
Got it. But don’t edit the main site unless I give the thumbs up

**Comment by Hardwaregore** [comment]
What is this?

**Comment by SirAlexBigBrain** [comment]
Please give me contributors access

**Comment by SirAlexBigBrain** [comment]
A site to make it look more professional

**Comment by SirAlexBigBrain** [comment]
I proposed a pull request. Accept it!

**Comment by SirAlexBigBrain** [comment]
When are you going to have the server?

**Comment by TechDudie** [comment]
when pigs fly

**Comment by SirAlexBigBrain** [comment]
I wasn’t talking to you!!

**Comment by TechDudie** [comment]
🐖 



🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲🌲

**Comment by SirAlexBigBrain** [comment]
Give me CONTRIBUTORS ACCSESS

**Comment by TechDudie** [comment]
ok

**Comment by SirAlexBigBrain** [comment]
Thanks

**Comment by TechDudie** [comment]
....if you star the repo

**Comment by TechDudie** [comment]
doit

**Comment by SirAlexBigBrain** [comment]
Got it

**Comment by TechDudie** [comment]
@SirAlexBigBrain STAR

**Comment by TechDudie** [comment]
if you ruin it BLEEP BLEEP BLE_**\[This content has been removed\]**_

**Comment by SirAlexBigBrain** [comment]
Sheesh

**Comment by TechDudie** [comment]
im not giving chinny access

**Comment by SirAlexBigBrain** [comment]
Ha ha ha

**Comment by TechDudie** [comment]
i think i broke it

**Comment by TechDudie** [comment]
bruh

**Comment by SirAlexBigBrain** [comment]
Are you copying and pasting from my file?

**Comment by SirAlexBigBrain** [comment]
You broke it

**Comment by SirAlexBigBrain** [comment]
No bad words remember the code of conduct

**Comment by SirAlexBigBrain** [comment]
Have you made the PayPal account

**Comment by Hardwaregore** [comment]
@TechDudie @SirAlexBigBrain 
—————————————————
TechDot and Mr.BrainBigGuy,
I am pretty sure I can get da server in around 2 months.
Sorry
Lol

[#]~$Hardwaregore

**Comment by SirAlexBigBrain** [comment]
Ahhhhhhhhhhhhhhhhhhhh

**Comment by Hardwaregore** [comment]
@TechDudie @SirAlexBigBrain
—————————————————
TechDot and Mr.BrainBigGuy,
Y don’t I have collab access on the new GrassBandits repo?

[#]~$Hardwaregore

**Comment by SirAlexBigBrain** [comment]
@TechDudie 
Yabo, read the comment above.

**Comment by SirAlexBigBrain** [comment]
Why

**Comment by SirAlexBigBrain** [comment]
Ha ha sucks

**Comment by SirAlexBigBrain** [comment]
I reopened the issue

**Comment by Hardwaregore** [comment]
Ok

**Comment by Hardwaregore** [comment]
Get @TechDudie  to give me collab
