### ISSUE TITLE
@Hardwaregore is inserting charecters so the code breaks and i have to fix this

### ISSUE THREAD

**Issue by TechDudie** [SirAlexBigBrain/GrassBandits#6]
ARGH @Hardwaregore QUIT IT

**Comment by TechDudie** [comment]
<img width="1280" alt="Screen Shot 2022-03-12 at 9 29 44 PM" src="https://user-images.githubusercontent.com/73961295/158043766-44e47f57-6df0-4d96-b140-b246394edfb2.png">

**Comment by Hardwaregore** [comment]
actually, it was a cerilic "e" in the indEx.html and the stylE.css

i’m sorry

**Comment by TechDudie** [comment]
I DONT CARE YOURE BREAKING IT STOP IT OR IM TALKING TO ALEX @SirAlexBigBrain

**Comment by TechDudie** [comment]
![F133DDDB-4CA2-4401-B2B9-83A21D87337D](https://user-images.githubusercontent.com/73961295/158077090-ab9480ac-a558-4188-a834-668c6d5b5d3b.jpeg)
