### ISSUE TITLE
Repo is extreamly unprofessional

### ISSUE THREAD

**Issue by Hardwaregore** [SirAlexBigBrain/GrassBandits#8]
@SirAlexBigBrain 
* Putting `\- *@*__SirAlexBigBrain (The Bee)__` in your readme is extremely unprofessional! You cant see the `\` or the `-` or the `*` or the `__`

* It is extremely unprofessional to make a release of HTML code especially when you aren't even done with it! You also shouldn't call a release `attempt`

**Comment by SirAlexBigBrain** [comment]
Go BLEEP yourself!
No  @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain #
@SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain

**Comment by Hardwaregore** [comment]
@SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain @SirAlexBigBrain
